# Generated by Django 3.0.2 on 2020-01-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelvedbook',
            name='finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shelvedbook',
            name='started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
