# Generated by Django 3.0.2 on 2020-01-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0002_auto_20200124_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelvedbook',
            name='status',
            field=models.IntegerField(choices=[(0, 'Want to read'), (1, 'Currently reading'), (2, 'Read')], default=0),
        ),
    ]
