# Generated by Django 3.0.2 on 2020-01-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0003_shelvedbook_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='shelvedbook',
            name='shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booktracker.Shelf'),
        ),
    ]
