# Generated by Django 3.0.2 on 2020-01-28 15:38

from django.db import migrations


def populate_shelves(apps, schema_editor):
    Shelf = apps.get_model('booktracker', 'Shelf')
    ShelvedBook = apps.get_model('booktracker', 'ShelvedBook')
    shelves = {shelf.id: shelf for shelf in Shelf.objects.all()}
    print(shelves)
    for shelved_book in ShelvedBook.objects.all():
        shelved_book.shelf = shelves[shelved_book.status + 1]
        shelved_book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0005_init_defaut_shelves'),
    ]

    operations = [
        migrations.RunPython(populate_shelves)
    ]
