# Generated by Django 3.0.2 on 2020-02-01 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booktracker', '0007_auto_20200128_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='shelved_by',
        ),
        migrations.AddField(
            model_name='book',
            name='shelved_to',
            field=models.ManyToManyField(through='booktracker.ShelvedBook', to='booktracker.Shelf'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelf',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelf',
            name='user_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shelvedbook',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktracker.Shelf'),
        ),
        migrations.AlterUniqueTogether(
            name='shelvedbook',
            unique_together={('book', 'shelf')},
        ),
        migrations.RemoveField(
            model_name='shelvedbook',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shelvedbook',
            name='user',
        ),
    ]
